// <auto-generated />
using LaShoppeeFinalVersion.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaShoppeeFinalVersion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210924093414_SeedingDb")]
    partial class SeedingDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LaShoppeeFinalVersion.Models.Books", b =>
                {
                    b.Property<int>("bookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bookDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bookImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bookImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("bookInStock")
                        .HasColumnType("bit");

                    b.Property<string>("bookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("bookOnSale")
                        .HasColumnType("bit");

                    b.Property<decimal>("bookPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.HasKey("bookId");

                    b.HasIndex("categoryId");

                    b.ToTable("bookies");

                    b.HasData(
                        new
                        {
                            bookId = 1,
                            bookDescription = "A fiction story about an indian girl by chetan bhagat",
                            bookImageThumbnailUrl = "\\Images\\OneIndianGirl.jpg",
                            bookImageUrl = "\\Images\\OneIndianGirl.jpg",
                            bookInStock = true,
                            bookName = "Onew Indian Girl",
                            bookOnSale = false,
                            bookPrice = 350m,
                            categoryId = 1
                        },
                        new
                        {
                            bookId = 2,
                            bookDescription = "A fiction story about an indian girl by chetan bhagat",
                            bookImageThumbnailUrl = "\\Images\\Fictiontwo.jpg",
                            bookImageUrl = "\\Images\\Fictiontwo.jpg",
                            bookInStock = true,
                            bookName = "Ray Bearer",
                            bookOnSale = false,
                            bookPrice = 399m,
                            categoryId = 1
                        },
                        new
                        {
                            bookId = 3,
                            bookDescription = "A fiction story about an indian girl by chetan bhagat",
                            bookImageThumbnailUrl = "\\Images\\Fictionthree.jpg",
                            bookImageUrl = "\\Images\\Fictionthree.jpg",
                            bookInStock = true,
                            bookName = "What People Won't Do",
                            bookOnSale = false,
                            bookPrice = 999m,
                            categoryId = 1
                        },
                        new
                        {
                            bookId = 4,
                            bookDescription = "A Non-fiction story about Squirrel Busy years",
                            bookImageThumbnailUrl = "\\Images\\nonfictiononee.jpg",
                            bookImageUrl = "\\Images\\nonfictiononee.jpg",
                            bookInStock = true,
                            bookName = "Squirrels Busy Year",
                            bookOnSale = false,
                            bookPrice = 1999m,
                            categoryId = 2
                        },
                        new
                        {
                            bookId = 5,
                            bookDescription = "A Non-fiction story about elephants and animals",
                            bookImageThumbnailUrl = "\\Images\\nonfictiontwoo.jpg",
                            bookImageUrl = "\\Images\\nonfictiontwoo.jpg",
                            bookInStock = true,
                            bookName = "Just So Stories",
                            bookOnSale = false,
                            bookPrice = 899m,
                            categoryId = 2
                        },
                        new
                        {
                            bookId = 6,
                            bookDescription = "A Non-fiction story about Penguins",
                            bookImageThumbnailUrl = "\\Images\\nonfictionthreee.jpg",
                            bookImageUrl = "\\Images\\nonfictionthreee.jpg",
                            bookInStock = true,
                            bookName = "Penguins",
                            bookOnSale = false,
                            bookPrice = 1899m,
                            categoryId = 2
                        },
                        new
                        {
                            bookId = 7,
                            bookDescription = "Adventure genre",
                            bookImageThumbnailUrl = "\\Images\\adventureone.jpg",
                            bookImageUrl = "\\Images\\adventureone.jpg",
                            bookInStock = true,
                            bookName = "The Leopard Princess",
                            bookOnSale = false,
                            bookPrice = 599m,
                            categoryId = 3
                        },
                        new
                        {
                            bookId = 8,
                            bookDescription = "Adventure genre on Dragon Run",
                            bookImageThumbnailUrl = "\\Images\\adventuretwo.jpg",
                            bookImageUrl = "\\Images\\adventuretwo.jpg",
                            bookInStock = true,
                            bookName = "Dragon Run",
                            bookOnSale = false,
                            bookPrice = 479m,
                            categoryId = 3
                        },
                        new
                        {
                            bookId = 9,
                            bookDescription = "Adventure genre on Dragon Run",
                            bookImageThumbnailUrl = "\\Images\\adventurethree.jpg",
                            bookImageUrl = "\\Images\\adventurethree.jpg",
                            bookInStock = true,
                            bookName = "The Town House",
                            bookOnSale = false,
                            bookPrice = 479m,
                            categoryId = 3
                        },
                        new
                        {
                            bookId = 10,
                            bookDescription = "Romantic love story",
                            bookImageThumbnailUrl = "\\Images\\romanticone.jpg",
                            bookImageUrl = "\\Images\\romanticone.jpg",
                            bookInStock = true,
                            bookName = "Love Song",
                            bookOnSale = false,
                            bookPrice = 879m,
                            categoryId = 4
                        },
                        new
                        {
                            bookId = 11,
                            bookDescription = "Romantic love story being Wild in Love",
                            bookImageThumbnailUrl = "\\Images\\romantictwo.jpg",
                            bookImageUrl = "\\Images\\romantictwo.jpg",
                            bookInStock = true,
                            bookName = "Wild In Love",
                            bookOnSale = true,
                            bookPrice = 379m,
                            categoryId = 4
                        },
                        new
                        {
                            bookId = 12,
                            bookDescription = "Romantic love story beast",
                            bookImageThumbnailUrl = "\\Images\\romanticthree.jpg",
                            bookImageUrl = "\\Images\\romanticthree.jpg",
                            bookInStock = false,
                            bookName = "Romantic and the Clock Work Beast",
                            bookOnSale = true,
                            bookPrice = 379m,
                            categoryId = 4
                        });
                });

            modelBuilder.Entity("LaShoppeeFinalVersion.Models.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            categoryId = 1,
                            categoryName = "Fiction Genre"
                        },
                        new
                        {
                            categoryId = 2,
                            categoryName = "Non-Fiction Genre"
                        },
                        new
                        {
                            categoryId = 3,
                            categoryName = "Thrilling Genre"
                        },
                        new
                        {
                            categoryId = 4,
                            categoryName = "Romantic Genre"
                        });
                });

            modelBuilder.Entity("LaShoppeeFinalVersion.Models.Books", b =>
                {
                    b.HasOne("LaShoppeeFinalVersion.Models.Category", "Category")
                        .WithMany("Bookies")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
