// <auto-generated />
using LaShoppeeFinalVersion.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaShoppeeFinalVersion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210924064821_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LaShoppeeFinalVersion.Models.Books", b =>
                {
                    b.Property<int>("bookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bookDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bookImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bookImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("bookInStock")
                        .HasColumnType("bit");

                    b.Property<string>("bookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("bookOnSale")
                        .HasColumnType("bit");

                    b.Property<decimal>("bookPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.HasKey("bookId");

                    b.HasIndex("categoryId");

                    b.ToTable("bookies");
                });

            modelBuilder.Entity("LaShoppeeFinalVersion.Models.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("LaShoppeeFinalVersion.Models.Books", b =>
                {
                    b.HasOne("LaShoppeeFinalVersion.Models.Category", "Category")
                        .WithMany("Bookies")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
